.SH NAME
.PP
Jekyll
.SH DESCRIPTION
.PP
Jekyll is a blog\-aware, static site generator built in Ruby
.SH COMMANDS
.PP
build      Build your site
doctor     Search site and print specific deprecation warnings
help       Display global or [command] help documentation
import     Import your old blog into Jekyll
new        Creates a new Jekyll site scaffold in PATH
serve      Serve your site locally
.SH ALIASES
.PP
hyde      doctor
server    server
.SH GLOBAL OPTIONS
.PP
\fB\fC-s\fR,\fB\fC--source\fR \fI[DIR]\fP
Source directory (defaults to ./)
.PP
\fB\fC-d\fR, \fB\fC--destination\fR \fI[DIR]\fP
Destination directory (defaults to ./_site) 
.SH BUGS
.PP
If you find a bug please head over to the issue tracker on github and
report it!  
.UR https://github.com/mojombo/jekyll/issues
.UE
.SH AUTHORS
.PP
By Tom Preston\-Werner, Nick Quaranto, and many awesome contributors!