.TH JEKYLL 1 "User Manual"
.SH NAME:
.PP
Jekyll
.SH DESCRIPTION:
.PP
Jekyll is a blog\-aware, static site generator built in Ruby
.SH COMMANDS:
.TP
\fB\fCbuild\fR
Build your site
.TP
\fB\fCdoctor\fR
Search site and print specific deprecation warnings
.TP
\fB\fChelp\fR
Display global or [command] help documentation
.TP
\fB\fCimport\fR
Import your old blog into Jekyll
.TP
\fB\fCnew\fR
Creates a new Jekyll site scaffold in PATH
.TP
\fB\fCserve\fR
Serve your site locally
.SH ALIASES:
.TP
hyde
doctor
.TP
serve
server
.SH GLOBAL OPTIONS:
.PP
\fB\fC-s\fR, \fB\fC--source\fR \fI[DIR]\fP
Source directory (defaults to ./)
.PP
\fB\fC-d\fR, \fB\fC--destination\fR \fI[DIR]\fP
Destination directory (defaults to ./_site) 
.PP
\fB\fC--safe\fR
Safe mode (defaults to false)
.PP
\fB\fCp\fR, \fB\fC--plugins PLUGINS_DIR1[,PLUGINS_DIR2[,...]]\fR
Plugins directory (defaults to ./_plugins)
.PP
\fB\fC--layouts STRING\fR
Layouts directory (defaults to ./_layouts)
.SH BUGS:
.PP
If you find a bug please head over to the issue tracker on github and
report it.  https://github.com/mojombo/jekyll/issues
.UR https://github.com/mojombo/jekyll/issues
.UE
.SH AUTHORS:
.PP
By Tom Preston\-Werner, Nick Quaranto, and many awesome contributors!