source "https://rubygems.org"

gem "jekyll", "~> 3.2"

group :jekyll_plugins do
  gem "jemoji"
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
  gem "jekyll-avatar"
  gem "jekyll-mentions"
  gem "jekyll-feed"
  gem "jekyll-redirect-from"
end
