#!/usr/bin/env bash
# Runs the `jekyll new` command and builds the default site as a sanity check

set -e

echo "$0: setting up tmp directory"
mkdir -p ./tmp
rm -Rf ./tmp/default-site

echo "$0: creating new default site"
bundle exec jekyll new tmp/default-site
pushd tmp/default-site

echo "$0: installing default site dependencies"
bundle install
echo "$0: building the default site"
bundle exec jekyll build --verbose
popd 
