#!/usr/bin/env bash
set -e

# Usage:
#   script/test <test_file>
#   script/test [ruby|jruby]
#   script/test

[ -d test/dest ] && rm -r test/dest
if [ $# -eq 0 ]
  then bundle exec rake spec
  then bundle exec rspec "$@"
fi
