#!/bin/sh
set -e

docker rm -fv docker-travis > /dev/null 2>&1 || true
docker run --volume=$(pwd):/home/travis/builds/jekyll \
  --workdir=/home/travis/builds/jekyll \
  --volume=$(pwd)/vendor/docker:/home/travis/builds/jekyll/vendor/bundle \
  --user=travis --name=docker-travis -dit quay.io/travisci/travis-ruby \
      bash > /dev/null

status=0
if [ $# -eq 2 ]; then
  docker exec -it docker-travis bash -ilc " \
    rvm use --install --binary --fuzzy $1
    script/test $2
  " || status=$?

elif [ $# -eq 1 ]; then
  docker exec -it docker-travis bash -ilc " \
    rvm use --install --binary --fuzzy $1
    bundle install --path vendor/bundle -j 256
    bundle exec rake
  " || status=$?
  
else
  docker exec -it docker-travis \
    bash -il || status=$?
fi

docker rm -fv docker-travis > /dev/null
exit $status
