#!/usr/bin/env ruby
# frozen_string_literal: true

STDOUT.sync = true

# Add the 'lib' directory to the load path for Ruby modules
$LOAD_PATH.unshift File.expand_path("../lib", __dir__)

require "jekyll"
require "mercenary"

# Load Jekyll plugins
Jekyll::PluginManager.require_from_bundler

# Process any deprecated options
Jekyll::Deprecator.process(ARGV)

# Define the command-line interface using the `Mercenary` library
Mercenary.program(:jekyll) do |p|

  # Define the version and description of the tool
  p.version Jekyll::VERSION
  p.description "Jekyll is a blog-aware, static site generator in Ruby"
  p.syntax "jekyll <subcommand> [options]"

  # Define options that can be passed to the tool
  p.option "source", "-s", "--source [DIR]", "Source directory for the Jekyll site (defaults to ./)"
  p.option "destination", "-d", "--destination [DIR]",
    "Destination directory (defaults to ./_site)"
  p.option "safe", "--safe", "Safe mode (defaults to false)"
  p.option "plugins_dir", "-p", "--plugins PLUGINS_DIR1[,PLUGINS_DIR2[,...]]", Array,
    "Plugins directory (defaults to ./_plugins)"
  p.option "layouts_dir", "--layouts DIR", String,
    "Layouts directory (defaults to ./_layouts)"
  p.option "profile", "--profile", "Generate a Liquid rendering profile"

  # Check for required gems and display an error message if they're not installed
  Jekyll::External.require_if_present(Jekyll::External.blessed_gems) do |g, ver_constraint|
    cmd = g.split("-").last
    p.command(cmd.to_sym) do |c|
      c.syntax cmd
      c.action do
        Jekyll.logger.abort_with "You must install the '#{g}' gem" \
          " version #{ver_constraint} to use the 'jekyll #{cmd}' command."
      end
    end
  end

  # Initialize each of the available subcommands
  Jekyll::Command.subclasses.each { |c| c.init_with_program(p) }

  # Define the default action if no subcommand is provided
  p.action do |args, _|
    if args.empty?
      Jekyll.logger.error "A subcommand is required."
      puts p
      abort
    else
      subcommand = args.first
      unless p.has_command? subcommand
        Jekyll.logger.abort_with "fatal: 'jekyll #{args.first}' could not" \
          " be found. You may need to install the jekyll-#{args.first} gem" \
          " or a related gem to be able to use this subcommand."
      end
    end
  end
end
