Feature: Create sites
  As a hacker who likes to blog
  I want to be able to make a static site
  In order to share my awesome ideas with the interwebs

  Scenario: Basic site
    Given I have a blank site
    And I have an "index.html" file that contains "Basic Site"
    When I run jekyll
    Then the _site directory should exist
    And I should see "Basic Site" in "_site/index.html"

  Scenario: Basic site with a post
    Given I have a blank site
    And I have a _posts directory
    And I have a post titled "Hackers" for "3/24/2009" that contains "My First Exploit"
    When I run jekyll
    Then the _site directory should exist
    And I should see "My First Exploit" in "_site/2009/03/24/hackers.html"

  Scenario: Basic site with layout and a page
    Given I have a blank site
    And I have a _layouts directory
    And I have an "index.html" file with a "default" layout that contains "Basic Site with Layout"
    And I have a default layout that contains "Page Layout: {{ content }}"
    When I run jekyll
    Then the _site directory should exist
    And I should see "Page Layout: Basic Site with Layout" in "_site/index.html"

  Scenario: Basic site with layout and a post
    Given I have a blank site
    And I have a _layouts directory
    And I have a _posts directory
    And I have a post titled "Wargames" for "3/26/2009" that contains "Would you like to play a game?"
    And I have a post titled "Wargames" for "3/26/2009" with layout "default"
    And I have a default layout that contains "Post Layout: {{ content }}"
    When I run jekyll
    Then the _site directory should exist
    And I should see "Post Layout: Would you like to play a game?" in "_site/2009/03/26/wargames.html"

  Scenario: Basic site with include tag
    Given I have a blank site
    And I have a _includes directory
    And I have an "index.html" file that contains "Basic Site with include tag: {% include about.html %}"
    And I have an "_includes/about.html" file that contains "Generated by Jekyll"
    When I run jekyll
    Then the _site directory should exist
    And I should see "Basic Site with include tag: Generated by Jekyll" in "_site/index.html"
