name: "Release, please!"

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
    - name: Run Release Please
      id: release
      uses: googleapis/release-please-action@v4
      with:
        config-file: .github/release-please-config.json
        manifest-file: .github/release-please-manifest.json
        token: ${{ secrets.JEKYLLBOT_TOKEN }}

  publish-gem:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    - name: Build and Publish Gem
      uses: rubygems/release-gem@v1
